#!/usr/bin/env bash

set -euo pipefail

QUIET=false

# Parse flags
while getopts "q" opt; do
  case $opt in
    q) QUIET=true ;;
  esac
done

# Redirección
if $QUIET; then
  OUT="/dev/null"
else
  OUT="/dev/stdout"
fi


echo "Iniciando servicios... (presiona 'q' + Enter para salir)"

# API
(
  cd api
  uvicorn admin:app --port 8000 >"$OUT" 2>&1 &

  uvicorn main:app --host 0.0.0.0 --port 8080 >"$OUT" 2>&1 &
)

# Frontend admin
(
  cd frontend/admin
  python -m http.server 5500 >"$OUT" 2>&1 &
)

# Frontend user
(
  cd frontend/user

  ADDR=$(hostname -i | awk '{print $1}')

  sed -i "305c\\const API = \"http://$ADDR:8080\";" index.html

  python -m http.server 5050 >"$OUT" 2>&1 &
  npx serve . >"$OUT" 2>&1 &
)

